### ISSUE TITLE
nesting unnamed elements

### ISSUE THREAD

**Issue by cgrad01** [ccml/prj-rev-bwfs-dasmoto#3]
this kind of styling, while fine for this small project, can become confusing in a larger application. If this was something like .items .brush { ... }, then I could let it slide, but since it is div h2 { ... } I feell like I should call it out. It will become impossible to remember why h2s are styled one way when they are in a div, vs when they are outside of one in the future. So it is best to avoid having this kind of logic in your future stylesheets.

https://github.com/ccml/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCraft/resources/css/style.css#L13

**Comment by ccml** [comment]
Changed!
