### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by cgrad01** [ccml/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations

This project looks good in the browser, shows a strong understanding of css selectors, and uses a nice and easy to understand html structure. I pointed an issue with the css selecting of nested elements. This is generally something to avoid, and don't be afraid to use classes, even in a small application. [A well named class ](http://bdavidxyz.com/blog/how-to-name-css-classes/)can go a long way to making your code more readable.

As a further challenge I would suggest adding an About Dasmoto page, and linking that to your homepage you have already made. You made need to review past lessons to do this but I think you are up to the challenge!

**Comment by ccml** [comment]
Done !
